version: "2"

services:
  mqtt-trigger:
    build: .
    environment:
      PORT: 8080
      ETCD_URLS: http://etcd:2379
      CONF: "./mqtt-trigger.yml"
    tty: true

  api:
    build: ./tests/api
    ports:
    - 3000:3000

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883   # MQTT
      - 9001:9001
    volumes:
      - /mosquitto/data
      - /mosquitto/log
#      - ./tests/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
