version: "2"

services:
  sut:
    build: ./tests/test
    command: npm test
    depends_on:
    - mqtt-trigger
    - etcd
    - mosquitto

  mqtt-trigger:
    build: .
    environment:
      PORT: 8080
      ETCD_URLS: http://etcd:2379
    ports:
    - 8088:8080
    tty: true

  etcd:
    image: "quay.io/coreos/etcd"
    volumes:
      - /usr/share/ca-certificates/:/etc/ssl/certs
    ports:
      - "4001:4001"
      - "2380:2380"
      - "2379:2379"
    #mem_limit: 128m
    environment:
      GOMAXPROCS: 2
    command:
    - /usr/local/bin/etcd
    - -advertise-client-urls=http://0.0.0.0:2379
    - -listen-client-urls=http://0.0.0.0:2379

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 9883:1883   # MQTT
      - 9001:9001
    volumes:
      - /mosquitto/data
      - /mosquitto/log
#      - ./tests/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
