version: "2"

services:
  sut:
    build: ./tests/test
    command: npm test
    depends_on:
    - mqtt-trigger
    - mosquitto

  mqtt-trigger:
    build: .
    environment:
      CONF: "./mqtt-trigger-test.yml"
    ports:
    - 8088:8080
    depends_on:
    - mosquitto

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 9883:1883   # MQTT
      - 9001:9001
#    volumes:
#      - /mosquitto/data
#      - /mosquitto/log
#      - ./tests/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
